name: rplab
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - numba
  - pandas
  - pytables
  - git
  - ffmpeg
  - scikit-image
  - scikit-learn
  - matplotlib
  - pyqt
  - opencv
  - h5py
  - av
  - jupyterlab
  - ipywidgets
  - ipympl
  - ffmpeg
  - imageio
  - nodejs
  - pip:
        - plotly
        - pyqtgraph
        - colorspacious
        - scikit-image
        - flammkuchen
        - black
        
